use btree_map for storing withdrawals mapped to the account
Polkadex-Substrate/polkadex-primitives pull request #23
Opened 2022-08-03 19:06 UTC by felixfaisal

Using a BTreeMap for storing withdrawals

2022-08-04 19:37 UTC, serhii-temchenko commented
Had discussion and a standup about this change with @35359595, please contact him about that.

2022-08-09 21:13 UTC, serhii-temchenko commented
If discussed improvement with tests of serialization is in progress - please remove `review` label.

2022-08-10 15:56 UTC, serhii-temchenko requested changes

2022-08-10 15:56 UTC, serhii-temchenko commented on src/snapshot.rs
> +    fn snpashot_serialize_deserialize(){
Typo

2022-08-10 15:56 UTC, serhii-temchenko commented on src/snapshot.rs
> +            withdrawals: withdrawals,
Can be simplified to `withdrawals`.

2022-08-10 15:56 UTC, serhii-temchenko commented on src/snapshot.rs
> +        let mut snapshot: BTreeMap<AccountId, AccountInfo<AccountId, Balance, ProxyLimit>> = Default::default();
Not used.

2022-08-10 15:56 UTC, serhii-temchenko commented on src/snapshot.rs
> +}
Please add empty line.

2022-08-15 05:55 UTC, felixfaisal commented on src/snapshot.rs
> +    fn snpashot_serialize_deserialize(){
Updated ✅

2022-08-15 05:56 UTC, felixfaisal commented on src/snapshot.rs
> +            withdrawals: withdrawals,
Updated ✅

2022-08-15 05:56 UTC, felixfaisal commented on src/snapshot.rs
> +        let mut snapshot: BTreeMap<AccountId, AccountInfo<AccountId, Balance, ProxyLimit>> = Default::default();
Updated ✅

2022-08-15 05:57 UTC, felixfaisal commented on src/snapshot.rs
> +}
Updated ✅

2022-08-15 18:45 UTC, serhii-temchenko commented on src/snapshot.rs
> +}
Wrong line. Please add at the end.

2022-08-16 06:51 UTC, serhii-temchenko approved these changes

2022-08-16 10:59 UTC, Gauthamastro approved these changes

2022-08-16 11:00 UTC, Gauthamastro commented
There should be a equivalent update to 0.9.19 branch too. @felixfaisal

2022-08-16 19:04 UTC, merged